vim.keymap.set("n", "<leader>pa", "<Cmd>Vp4Annotate<CR>")
vim.keymap.set("n", "<leader>pd", "<Cmd>Vp4Diff<CR>")
vim.keymap.set("n", "<leader>pe", "<Cmd>Vp4Edit<CR>")
vim.keymap.set("n", "<leader>pl", "<Cmd>Vp4Filelog<CR>")
vim.keymap.set("n", "<leader>pq", "<Cmd>Vp4Revert<CR>")
